### PR TITLE
Create VMax

### PR DESCRIPTION
**Pull request by jeeve**
Python script to display velocity max of files

### CODE REVIEW

**Comment by JuanIrache** [comment]
Hi @jeeve 

I'm not sure adding Phyton code to the repo is the best idea, as it's already a bit confusing with the go and batch code.

What do you think?

**Comment by jeeve** [comment]
No problem, I understand
Thanks for your job
jeeve

Le mer. 8 avr. 2020 à 21:48, Juan Irache <notifications@github.com> a
écrit :

**Comment by sbonaime** [comment]
Hi @JuanIrache 
I am thinking about creating either a GPMD2CSV.sh or GPMD2CSV.py for the non windows users. Maybe the Python script could be more useful ? 
What do you think ?

**Comment by JuanIrache** [comment]
@sbonaime If you come up with a file structure that makes sense with the current one, I would say go for it. This repo is very outdated, though. My JavaScript parsing tools are way way more comprehensive, so you might want to consider basing it off of that instead: https://github.com/JuanIrache/gopro-telemetry

**Pull request closed without merging**
